name: Bell Conductor
version: 0.0.1
build: 1
encrypt stacks: false
multiple instances: false
relaunch in background: false
application data folder:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
creator code:
shutdown when all windows are closed: false
preferences:
  user:
    macos:
      filename: com.trevordevore.bellconductor
    windows:
      filename: com.trevordevore.bellconductor
    ios:
      filename: com.trevordevore.bellconductor
ui:
  1:
    folder: ./ui
libraries:
  1:
    folder: ./libraries
frontscripts:
  1:
    folder: ./frontscripts
backscripts:
  1:
    folder: ./backscripts
behaviors:
  1:
    folder: ./behaviors
helpers:
  1:
    filename: {{FRAMEWORK}}/helpers/preferences
build folder: ../builds
build profiles:
  all profiles:
    post build script:
    certificates:
      macos:
        name:
  release:
  beta:
